name: parallax_swiper_example
description: An example of the use of parallax_swiper.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  parallax_swiper:
    path: ../



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: SuperMario
      fonts:
       - asset: fonts/SuperMario256.ttf

